### ISSUE TITLE
How to start postgres?

### ISSUE THREAD

**Issue by Hannibal2** [Sunghee2/myongstagram#1]
Cant run this app when I copy into console "psql postgres
  >  CREATE ROLE myongstagram WITH LOGIN CREATEDB PASSWORD 'myongstagram';
It told me that comand not found.
Really cool app, I am want to run it very much. Please help me!

**Comment by Sunghee2** [comment]
Hello!
Did you add the PostgreSQL bin directory path to the PATH environmental variable after installing postgresql?
This enables you to use the command `psql` to start the PostgreSQL command-line tool(psql) from the Windows Command Prompt.
then, you should run a `psql postgres` command and enter your password.
After doing this, you should run a `CREATE ROLE myongstagram WITH LOGIN CREATEDB PASSWORD 'myongstagram';` command to create a `myongstagram` user.
I hope this helps you😊.
